apiVersion: batch/v1
kind: Job
metadata:
  name: test-hello
spec:
  backoffLimit: 5
  template:
    spec:
      containers:
      - name: demoapp
        image: astravinskyigl/demoapp:v1.1.1
      restartPolicy: OnFailure
