name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_HUB_REPO: demoapp
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install autotag
      run: curl -sL https://git.io/autotag-install | sudo sh -s -- -b /usr/bin
      
    - name: preconfigure to autotag
      run: |
        git fetch --tags --unshallow --prune;

        if [ $(git rev-parse --abbrev-ref HEAD) != "master" ]; then
          # ensure a local 'master' branch exists at 'refs/heads/master'
          git branch --track master origin/master
        fi
      
    - name: Add tag to the build
      run: autotag --scheme=conventional
      
    - name: Get the last tag
      run: export TAG=$(git tag)
      
    - name: Show
      run: echo $TAG
      
#     - name: Get the version
#       id: get_version
#       run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
#     - name: Login to DockerHub
#       run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag $DOCKER_USER/$DOCKER_HUB_REPO:${{ steps.get_version.outputs.VERSION }} --tag $DOCKER_USER/$DOCKER_HUB_REPO:latest

#     - name: Push image to the Docker Hub
#       run: docker push --all-tags $DOCKER_USER/$DOCKER_HUB_REPO
