name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_HUB_REPO: demo-app
    
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/demoapp:$(date +%s) --tag $DOCKER_USER/demoapp:latest

    - name: Push image to the Docker Hub
      run: docker push --all-tags $DOCKER_USER/demoapp
